version: "3"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "7000"
        environment:
            - PORT=7000
        restart: always
    nginx:
        image: nginx:1.21.4-alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - api
        restart: always
