/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface ISupportsFeeInterface extends utils.Interface {
  functions: {
    "feePercent()": FunctionFragment;
    "feeRecipient()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "feePercent" | "feeRecipient"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "feePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "feePercent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ISupportsFee extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISupportsFeeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    feePercent(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { percent: BigNumber; denominator: BigNumber }
    >;

    feeRecipient(
      overrides?: CallOverrides
    ): Promise<[string] & { recipient: string }>;
  };

  feePercent(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { percent: BigNumber; denominator: BigNumber }
  >;

  feeRecipient(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    feePercent(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { percent: BigNumber; denominator: BigNumber }
    >;

    feeRecipient(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    feePercent(overrides?: CallOverrides): Promise<BigNumber>;

    feeRecipient(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    feePercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeRecipient(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
